### ISSUE TITLE
todo - nov 25, 2022

### ISSUE THREAD

**Issue by hanniabu** [etheralpha/rocketpool-community#4]
- [x] rename 2022-03-10--InvisibleSymbol.png to 2022-03-10--Patches.png
- [x] fix meme attribution bug
- [x] fix "View random" placeholder bug

**Comment by hanniabu** [comment]
https://github.com/etheralpha/rocketpool-community/pull/5
