### ISSUE TITLE
todo - nov 28, 2022

### ISSUE THREAD

**Issue by hanniabu** [etheralpha/rocketpool-community#6]
- [x] add poap: 
  - [x] https://poap.gallery/event/87858
  - [x] https://poap.gallery/event/91174
  - [x] https://poap.gallery/event/90470
  - [x] https://poap.gallery/event/88812
  - [x] https://poap.gallery/event/91008
  - [x] https://poap.gallery/event/91005
  - [x] https://poap.gallery/event/84157
  - [x] https://poap.gallery/event/92549
  - [x] https://poap.gallery/event/93088 (sleety)
  - [x] https://poap.gallery/event/93200 (mao)
  - [x] https://poap.gallery/event/95433
  - [x] https://poap.gallery/event/95872 (poapathon - payjoe93)
  - [x] https://poap.gallery/event/96093 (ShfRyn)
  - [x] https://poap.gallery/event/96545 (ShfRyn)
  - [x] https://poap.gallery/event/96625 (ShfRyn)
  - [x] https://poap.gallery/event/93461 (see desc)
  - [x] https://poap.gallery/event/95942 (kane)
  - [x] https://poap.gallery/event/98079 (gitpoap)
  - [x] https://poap.gallery/event/98082 (gitpoap)
  - [x] https://poap.gallery/event/98169 (ShfRyn)
  - [ ] https://poap.gallery/event/98651 (ShfRyn)
  - [ ] https://poap.gallery/event/98878
  - [ ] https://poap.gallery/event/99307 (ShfRyn)
  - [ ] https://poap.gallery/event/100149 (takezo)
  - [ ] https://poap.gallery/event/100300 (ShfRyn)
  - [ ] https://poap.gallery/event/100680 (ShfRyn)
  - [ ] https://poap.gallery/event/100465 (mentor?)
  - [ ] https://poap.gallery/event/100490 (ShfRyn)
  - [ ] https://poap.gallery/event/100488 (ShfRyn)
  - [ ] https://poap.gallery/event/100485 (ShfRyn)
  - [ ] https://poap.gallery/event/98878
  - [ ] https://poap.gallery/event/102475 (rplmaxi.eth)
  - [ ] https://poap.gallery/event/104402 (rplmaxi.eth)
  - [ ] https://poap.gallery/event/105622 (ShfRyn)
  - [ ] https://poap.gallery/event/92349
  - [ ] https://poap.gallery/event/102064 (poapathon)
  - [ ] https://poap.gallery/event/105512 (woh)
  - [ ] https://poap.gallery/event/102190
  - [ ] https://poap.gallery/event/101323
  - [ ] https://poap.gallery/event/105622
  - [ ] https://poap.gallery/event/106846
  - [ ] https://poap.gallery/event/107045
  - [ ] https://poap.gallery/event/107048
  - [ ] https://poap.gallery/event/107057
  - [ ] https://poap.gallery/event/107321
  - [ ] https://poap.gallery/event/108345 (rplmaxi.eth#1328)
  - [ ] https://poap.gallery/event/108762
  - [ ] https://poap.gallery/event/109211
  - [ ] https://poap.gallery/event/111015
  - [ ] https://poap.gallery/event/116392
  - [ ]  https://poap.gallery/event/116840
  - [ ]  https://poap.gallery/event/117242
  - [ ]  https://poap.gallery/event/117967
  - [ ]  https://poap.gallery/event/122427
  - [ ] https://poap.gallery/event/122884 (ShfRyn)
  - [ ] https://poap.gallery/event/123059 (from ethstaker)
  - [ ] https://poap.gallery/event/123108
  - [ ] https://poap.gallery/event/124627 (sleety)
  - [ ] https://poap.gallery/event/124904 (drdoofus)
  - [ ] https://poap.gallery/event/126367 (drdoofus)
  - [ ] https://poap.gallery/event/126012 (rplgrime)
  - [ ] https://poap.gallery/event/126150 (rplgrime)
  - [ ] https://poap.gallery/event/126830 (shfryn)
  - [ ] https://poap.gallery/event/127019 (rplgrime)
  - [ ] https://poap.gallery/event/127287 (shfryn)
  - [ ] https://poap.gallery/event/144279
  - [ ] https://poap.gallery/event/147430
  - [ ] https://poap.gallery/event/
  - [ ] 
- [ ] link to poap stickers by Vail#5913
- [x] bookmark:
  - [x] binance listing https://discord.com/channels/405159462932971535/405163713063288832/1065118728225828884
- [ ] update memes
- [x] add Kushim pet
- [x] notification and toast expirations
- [x] add thesis from bots Rocket Pool Investment Theses command info
- [x] add setting for bootstrap includes
- [x] update buy rpl guide to include gate.io https://twitter.com/crypto_alerting/status/1612730144514314241
- [x] add https://stakerocketpool.xyz/ to projects, made by ?
- [x] add nfts:
  - [x] https://opensea.io/assets/ethereum/0x0447433bd197f03be984a6053241ae8d347c5539/120
- [ ] add poap and graveyard: 
  - [ ] https://discord.com/channels/405159462932971535/1071118068304064533/1071564785109455018
  - [ ] https://discord.com/channels/405159462932971535/405163713063288832/1048397774347047042
  - [ ] https://discord.com/channels/888468681435271209/1059316607698079834
  - [ ] https://discord.com/channels/888468681435271209/1055162364716142702
  - [ ] https://discord.com/channels/888468681435271209/1048454420725239808
  - [ ] https://discord.com/channels/888468681435271209/1042627274211590264
  - [ ] https://discord.com/channels/405159462932971535/888891692432883712/888899842569560105
  - [ ] https://poap.vote/poll/312
- [x] add odao dashboard by greywizard: https://dune.com/greywizard/rocket-pool-odao-stats
- [x] add coinbase link to buy rpl post: https://pro.coinbase.com/trade/RPL-USD
- [x] add butta sunglasses to asset library
- [x] add raffles:
  - [x] https://poap.fun/raffle/1936
- [ ] add resources
  - [ ] https://docs.google.com/document/d/1XiOPWMjG5_BBxF5G5MafZc9Cde24y9jp-iKWKZsJxpk/
  - [ ] https://dune.com/greywizard/rocket-pool-odao-stats
  - [ ] https://store.palokaj.co/rocketpool/ , made by mentor
  - [ ] https://0xhodja.netlify.app/posts/rocketpool_node_distribution , made by Hodja#0746
  - [ ] https://github.com/xrchz/rockettrack , made by ramana#2626
  - [ ] https://github.com/htimsk/SPanalysis by ken
  - [ ] https://twitter.com/Defi_Map/status/1642930745672085505
  - [ ] https://dune.com/drworm/rocketpool drworm.eth#9345
  - [ ] https://www.reddit.com/r/rocketpool/comments/14ec26i/i_made_a_new_and_improved_rp_income_calculator/ by yogofubi
  - [ ] https://dune.com/queries/2369881 drworm.eth#9345
  - [ ] https://rocketpool-odao-treegen-game.netlify.app/?&salt=5167
  - [ ] https://dune.com/NDGcrypto/Rocket-Pool-rETH-and-Nodes
  - [ ] https://gist.github.com/jshufro/744e0b45d6ef0012e01f99f78023728d
  - [ ] https://github.com/trevhub/guides/blob/main/CheapUPS.md
  - [ ] https://docs.google.com/spreadsheets/d/18T5w_w9uf6eOy5tt3GDNLFjNp7pr__1Z9IaW4RBCAQY/
  - [ ] https://sp.sprocketpool.net/public-dashboards/480c3d119bc04d7c9e7069feeb4f1445?orgId=1&refresh=2h
  - [ ] https://dune.com/rp_community/lst-comparison
  - [ ] defi opportunities https://docs.google.com/document/d/1XiOPWMjG5_BBxF5G5MafZc9Cde24y9jp-iKWKZsJxpk/edit by Val#5027
  - [ ] https://gist.github.com/0xobjectObject/b0287964cbada9e6bf6bc67c58846818
  - [ ] https://rocketpool-odao-treegen-game.netlify.app/
  - [ ] https://0xhodja.netlify.app/posts/rocketpool_odao_gas_costs_2023_01_26/
  - [ ] https://0xhodja.netlify.app/posts/rocketpool_odao_gas_costs_2023_01_27/
  - [ ] https://app.alphaday.com/b/rocketpool
  - [ ] sp.sprocketpool.net
  - [ ] delete vgr dashboard
  - [ ] https://docs.google.com/spreadsheets/d/1MAn9zXuFm1U4Ysb8RQpC3D_tFg99diRKyWPSQ13ha9E/ 10validations.eth#5655
  - [ ] https://docs.google.com/spreadsheets/d/1d4DuLa4KqAn9nS3J85m4Oou979ykgC8UQRcqJGbRHbk/ Cayos#9269
  - [ ] https://grafana.com/grafana/dashboards/18391-rocket-pool-dashboard-v1-2-0/
  - [ ] https://rocketpool.karmahq.xyz/
- [x] add projects:
  - [x] https://store.palokaj.co/rocketpool/ , made by mentor
  - [x] https://0xhodja.netlify.app/posts/rocketpool_node_distribution , made by Hodja#0746
  - [x] https://rocketarb-watch.netlify.app/ , made by Hodja#0746
  - [x] https://github.com/xrchz/rockettrack , made by ramana#2626
  - [x] poap stickers, made by Vail#5913
  - [x] defi opportunities https://docs.google.com/document/d/1XiOPWMjG5_BBxF5G5MafZc9Cde24y9jp-iKWKZsJxpk/edit by Val#5027
 - [x] video: https://www.youtube.com/watch?v=1DQ7W-EvKuU
 - [ ] video: https://www.youtube.com/watch?v=UZRN9kqvOXY
 - [ ] merge in issue template
 - [ ] link to rpips
 - [ ] nfts
   - [ ] https://opensea.io/assets/matic/0x6c84d94e7c868e55aaabc4a5e06bdfc90ef3bc72/20306 from QiDao ethdenver scavenger hunt
 - [ ] pets
   - [ ] fix pets page description
   - [ ] add dybsy doggo Echo, Male, Whippet
 - [ ] thesis
   - [ ] https://docs.google.com/spreadsheets/d/1iw5BVCh91YCVX_WSk2a4UAygusrGkpKCbpwxu43CJX0/edit?usp=sharing FeelinGoodFeelinGreat
- [ ] update asset library
- [ ] update audits https://rocketpool.net/#security
- [ ] forward revenue page and rocketpooltool.com to official rp calc
- [ ] saas page.... https://stake.blockscape.network/ethereum/ https://www.allnodes.com/rpl/staking
- [ ] Hi everyone, just want to mention that the Sigma Prime links on: https://rocketpool.community/audits/ are not functioning.
- [ ] https://poap.fun/2193
